tasks:
  - name: Install k6
    init: |
      go install go.k6.io/xk6/cmd/xk6@latest
      xk6 build --with github.com/grafana/xk6-output-prometheus-remote@latest
      mv k6 /usr/bin/k6
  - name: Run prometheus
    command: |
      docker run -d -p 9090:9090 prom/prometheus \
        --enable-feature=remote-write-receiver
  - name: Run grafana
    command: |
      docker run -d -p 4000:4000 grafana/grafana:latest